sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aviquez96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aviquez96/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-925987319168"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY