sudo: required
language: generic

services:
  - docker

before_isntall:
  - docker build -t aviquez96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aviquez96/docker-react npm run test